<a href="https://colab.research.google.com/github/rashida048/Tensorflow/blob/main/Custom_and_Distributed_Training/TensorBasics_and_GradientTape.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
import numpy as np

In [2]:
def tf_constant(array):
  return tf.constant(array)

In [3]:
tar = np.arange(1, 10)
x = tf_constant(tar)
x

<tf.Tensor: shape=(9,), dtype=int64, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [4]:

def tf_cube(ar):
  ar = tf.constant(ar) 
  tf_squared_ar = ar**2 
  return tf_squared_ar               

In [5]:
tar = np.arange(1, 10)
x = tf_cube(tar)
x

<tf.Tensor: shape=(9,), dtype=int64, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])>

In [6]:
def tf_reshape(array, shape):
    """
    Args:
        array (EagerTensor): tensor to reshape.
        shape (tuple): desired shape.

    Returns:
        EagerTensor: reshaped tensor.
    """
    # make sure it's a tensor
    array = tf.constant(array)
    ### START CODE HERE ###
    tf_reshaped_array = tf.reshape(array, shape = shape)  
    ### END CODE HERE ###
    return tf_reshaped_array

In [7]:
tmp_array = np.array([1,2,3,4,5,6,7,8,9])
# Check that your function reshapes a vector into a matrix
x = tf_reshape(tmp_array, (3, 3))
x

<tf.Tensor: shape=(3, 3), dtype=int64, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])>

In [10]:
def tf_cast(array, dtype):
  array = tf.constant(array)
  tf_cast_array = tf.cast(array, dtype = tf.uint32)
  return tf_cast_array

In [11]:
tmp_array=[1, 2, 3, 4]
x = tf_cast(tmp_array, tf.float32)
x

<tf.Tensor: shape=(4,), dtype=uint32, numpy=array([1, 2, 3, 4], dtype=uint32)>

In [12]:
def tf_multiply(tensor1, tensor2):
  tensor1 = tf.constant(tensor1)
  tensor2 = tf.constant(tensor2)

  product = tf.multiply(tensor1, tensor2)

  return product

In [14]:
tmp_1 = tf.constant(np.array([[1, 2], [3, 4]]))
tmp_2 =tf.constant(np.array(2))
result = tf.multiply(tmp_1, tmp_2)
result

<tf.Tensor: shape=(2, 2), dtype=int64, numpy=
array([[2, 4],
       [6, 8]])>

In [15]:
# Add tensor1 and tensor2
def tf_add(tensor1, tensor2):
    """
    Args:
        tensor1 (EagerTensor): a tensor.
        tensor2 (EagerTensor): another tensor.

    Returns:
        EagerTensor: resulting tensor.
    """
    # make sure these are tensors
    tensor1 = tf.constant(tensor1)
    tensor2 = tf.constant(tensor2)
    
    ### START CODE HERE ###
    total = tf.add(tensor1, tensor2) 
    ### END CODE HERE ###
    return total

In [16]:
# Check your function
tmp_1 = tf.constant(np.array([1, 2, 3]))
tmp_2 = tf.constant(np.array([4, 5, 6]))
tf_add(tmp_1, tmp_2)

# Expected output:
# <tf.Tensor: shape=(3,), dtype=int64, numpy=array([5, 7, 9])>

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([5, 7, 9])>

In [17]:
def tf_gradient_tape(x):
    """
    Args:
        x (EagerTensor): a tensor.

    Returns:
        EagerTensor: Derivative of z with respect to the input tensor x.
    """
    with tf.GradientTape() as t:
        
    ### START CODE HERE ###
        # Record the actions performed on tensor x with `watch`
        t.watch(x)   

        # Define a polynomial of form 3x^3 - 2x^2 + x
        y = 3*(x**3) - 2*(x**2) + x 

        # Obtain the sum of the elements in variable y
        z = tf.reduce_sum(y) 
  
    # Get the derivative of z with respect to the original input tensor x
    dz_dx = t.gradient(z,x)
    ### END CODE HERE
    
    return dz_dx

In [18]:
# Check your function
tmp_x = tf.constant(2.0)
dz_dx = tf_gradient_tape(tmp_x)
result = dz_dx.numpy()
result

# Expected output:
# 29.0

29.0