<a href="https://colab.research.google.com/github/rashida048/Tensorflow/blob/main/Custom_and_Distributed_Training/tensor_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

Creating tensors with tf.Variable

In [2]:
model = tf.keras.Sequential([
    tf.keras.layers.Dense(1, input_shape=(1,))
])

In [3]:
model.variables

[<tf.Variable 'dense/kernel:0' shape=(1, 1) dtype=float32, numpy=array([[1.6824073]], dtype=float32)>,
 <tf.Variable 'dense/bias:0' shape=(1,) dtype=float32, numpy=array([0.], dtype=float32)>]

In [4]:
vector = tf.Variable(initial_value=[1, 2])
vector

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([1, 2], dtype=int32)>

In [5]:
vector = tf.Variable(initial_value=[1, 2], dtype=tf.float32)
vector

<tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([1., 2.], dtype=float32)>

In [6]:
vector = tf.Variable([[1, 2], [3, 4]])
vector

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [7]:
vector = tf.Variable([1, 2, 3, 4], shape=tf.TensorShape(None))
vector

<tf.Variable 'Variable:0' shape=<unknown> dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [8]:
mammal= tf.Variable("Elephant", dtype=tf.string)
its_complicated=tf.Variable(4 + 3j,
                            dtype=tf.complex64) 

In [9]:
mammal

<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'Elephant'>

In [10]:
its_complicated

<tf.Variable 'Variable:0' shape=() dtype=complex64, numpy=(4+3j)>

In [11]:
first_primes = tf.Variable([2, 3, 5, 7, 11],
                           dtype=tf.int32)
first_primes

<tf.Variable 'Variable:0' shape=(5,) dtype=int32, numpy=array([ 2,  3,  5,  7, 11], dtype=int32)>

In [12]:
linear_squares=tf.Variable([[4, 9], [16, 25]], dtype=tf.int32)
linear_squares

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[ 4,  9],
       [16, 25]], dtype=int32)>

In [13]:
tensor = tf.constant([1, 2, 3])
tensor

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [14]:
tensor = tf.constant([1, 2, 3, 4, 5, 6], shape=(2, 3))
tensor

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [15]:
tensor = tf.constant(-1.0, shape=(2, 3))
tensor

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[-1., -1., -1.],
       [-1., -1., -1.]], dtype=float32)>

In [18]:
import numpy as np
x = np.arange(0, 25)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [19]:
x = tf.constant(x)

In [20]:
x

<tf.Tensor: shape=(25,), dtype=int64, numpy=
array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])>

In [21]:
x = tf.square(x)
x

<tf.Tensor: shape=(25,), dtype=int64, numpy=
array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576])>

In [22]:
x = tf.reshape(x, (5, 5))
x

<tf.Tensor: shape=(5, 5), dtype=int64, numpy=
array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361],
       [400, 441, 484, 529, 576]])>

In [23]:
x = tf.cast(x, tf.float32)
x

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[  0.,   1.,   4.,   9.,  16.],
       [ 25.,  36.,  49.,  64.,  81.],
       [100., 121., 144., 169., 196.],
       [225., 256., 289., 324., 361.],
       [400., 441., 484., 529., 576.]], dtype=float32)>

In [25]:
y = tf.constant(2, dtype=tf.float32)
y

<tf.Tensor: shape=(), dtype=float32, numpy=2.0>

In [26]:
tf.multiply(x, y)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[   0.,    2.,    8.,   18.,   32.],
       [  50.,   72.,   98.,  128.,  162.],
       [ 200.,  242.,  288.,  338.,  392.],
       [ 450.,  512.,  578.,  648.,  722.],
       [ 800.,  882.,  968., 1058., 1152.]], dtype=float32)>

In [27]:
y = tf.constant([1, 2, 3, 4, 5], dtype=tf.float32)
y

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([1., 2., 3., 4., 5.], dtype=float32)>

In [28]:
x+y

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[  1.,   3.,   7.,  13.,  21.],
       [ 26.,  38.,  52.,  68.,  86.],
       [101., 123., 147., 173., 201.],
       [226., 258., 292., 328., 366.],
       [401., 443., 487., 533., 581.]], dtype=float32)>

In [29]:
x = 2
x_squared = tf.square(x)
print("hello, {}".format(x_squared))

hello, 4


In [30]:
a = tf.constant([[1, 2],
                 [3, 4]])
tf.add(a, 1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [4, 5]], dtype=int32)>

In [31]:
a = tf.constant([[1, 2],
                 [3, 4]])

a**2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 1,  4],
       [ 9, 16]], dtype=int32)>

In [32]:
a = tf.constant(5)
b = tf.constant(3)
np.multiply(a, b)

15

In [33]:
ndarray = np.ones([3, 3])
ndarray

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [34]:
tensor = tf.multiply(ndarray, 3)
tensor

<tf.Tensor: shape=(3, 3), dtype=float64, numpy=
array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])>

In [35]:
tensor.numpy()

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])

In [36]:
v = tf.Variable(0.0)
v+1

<tf.Tensor: shape=(), dtype=float32, numpy=1.0>

In [37]:
v =tf.Variable(0.0)
v.assign_add(1)

<tf.Variable 'UnreadVariable' shape=() dtype=float32, numpy=1.0>

In [38]:
v =tf.Variable(0.0)
v.assign_add(1)
v.read_value().numpy()

1.0

In [39]:
class MyLayer(tf.keras.layers.Layer):
  def __init__(self):
    super(MyLayer, self).__init__()
    self.my_var = tf.Variable(100)
    self.my_other_var_list = [tf.Variable(x) for x in range(2)]


m = MyLayer()
m

In [42]:
[variable.numpy() for variable in m.variables]

[100, 0, 1]